site_name: ServiceX
site_url: https://servicex.readthedocs.io/
nav:
    - Home: index.md
    - Introduction: introduction.md
    - 'User Guide': 'https://servicex-frontend.readthedocs.io/'
    - 'Deployment Guide':
        - Basic deployments: deployment/basic.md
        - Production deployments: deployment/production.md
        - Columnar Data Output Options: deployment/output_options.md
        - Reference: deployment/reference.md
        - User Management: deployment/user_management.md
    - 'Developer Guide':
        - Architecture: development/architecture.md
        - Contributing: development/contributing.md
plugins:
    - mkdocs-jupyter
theme:
    name: material
    features:
        - navigation.tabs
    logo: img/ServiceX-Color-Transparent.png