{{- if .Values.dataLifecycle.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-data-lifecycle-job
spec:
  schedule: {{ .Values.dataLifecycle.schedule | default  "* */8 * * *" | quote  }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}-data-lifecycle-job
        spec:
          containers:
          - name: {{ .Release.Name }}-data-lifecycle-job
            image: {{ .Values.dataLifecycle.image }}:{{ .Values.dataLifecycle.tag }}
            imagePullPolicy: {{ .Values.dataLifecycle.pullPolicy }}
            env:
              - name: RETENTION_PERIOD
                value: {{ .Values.dataLifecycle.retention }}

            command:
            - /bin/sh
            - -c
            - |
              CUTOFF_TIMESTAMP=$(date -d "$RETENTION_PERIOD" +%Y-%m-%dT%H:%M:%S) &&
              echo "Request data lifecycle with cutoff timestamp: $CUTOFF_TIMESTAMP" &&
              curl --request POST "http://{{ .Release.Name }}-servicex-app:8000/servicex/internal/data-lifecycle?cutoff_timestamp=$CUTOFF_TIMESTAMP"
          restartPolicy: OnFailure
{{- end }}
